lontongistic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('admin/', admin.site.urls)
]

main/urls.py
from django.urls import path
from main.views import create_product_flutter, show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user, remove_item, increase_item_amount, decrease_item_amount
from main.views import get_item_json, add_item_ajax, delete_item_ajax

app_name = 'main'

urlpatterns = [
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('json/', show_json, name='show_json'),
    path('xml/', show_xml, name='show_xml'), 
    path('create-product', create_product, name='create_product'),
    path('', show_main, name='show_main'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('remove_item/<int:id>/', remove_item, name='remove_item'),
    path('increase_item_amount/<int:id>/', increase_item_amount, name='increase_item_amount'),
    path('decrease_item_amount/<int:id>/', decrease_item_amount, name='decrease_item_amount'),
    path('get-product/', get_item_json, name='get_item_json'),
    path('add-item-ajax/', add_item_ajax, name='add_item_ajax'),
    path('delete-item-ajax/<int:id>/', delete_item_ajax, name='delete_item_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, name='name')
    amount = models.IntegerField(name='amount', validators=[MinValueValidator(0)])
    description = models.TextField(name='description')
    category = models.TextField (name='category')
    date_added = models.DateTimeField(auto_now_add=True, name='date_added')
    

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ProductForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description", "category"]
        

main/views.py
import datetime
import json
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from main.forms import ProductForm
from main.models import Item
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    items_total = items.count()
    
    context = {
        'app' : 'Lontongistic',
        'name': request.user.username,
        'class': 'PBP C',
        'items' : items,
        'items_total' : int(items_total),
        'last_login' : request.COOKIES['last_login']
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def increase_item_amount(request, id):
    item = get_object_or_404(Item, pk=id)
    item.amount += 1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def decrease_item_amount(request, id):
    item = get_object_or_404(Item, pk=id)
    if item.amount > 0:
        item.amount -= 1
        if item.amount == 0:
            item.delete()
        else:
            item.save()
    
    return HttpResponseRedirect(reverse('main:show_main'))

def remove_item(request, id):
    item = get_object_or_404(Item, pk=id)
    item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def get_item_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        category = request.POST.get("category")
        description = request.POST.get("description")
        user = request.user

        new_product = Item(name=name, amount=amount, category=category, description=description, user=user)
        new_product.save()


        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def delete_item_ajax(request, id):
    item = Item.objects.get(pk=id)
    item.delete()
    return HttpResponse(b"DELETED", status=201)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            category = data["category"],
            description = data["description"]
        )
        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<style>
</style>

<div class="create_product" style="background-image:url(https://cdn.visiteliti.com/article/2021-06/24/hihzEc6OEhQhDbao9DHi_1624529212.jpg); background-size: cover; background-position: center; background-repeat: no-repeat; background-size: cover;">
    <section class="vh-100" style="backdrop-filter: blur(20px);">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100" style="padding: 10px;">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card shadow-2-strong" style="border-radius: 1rem; background-color: whitesmoke;">
                        <div class="card-body p-5 text-center">
                            <form method="POST" action="">
                                {% csrf_token %}
                                <h1 class="mb-5" style="font-weight: bold; padding: 0px">Add New Item</h1>
                                <div class="form-outline mb-4">
                                    <input type="text" name="name" placeholder="Item Name" class="form-control" >
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="number" name="amount" placeholder="Amount" class="form-control" min="1">
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="text" name="category" placeholder="Category" class="form-control">
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="text" name="description" placeholder="Description" class="form-control" style="height: 100px;">
                                </div>
                                <input class="btn btn-primary btn-lg btn-block" type="submit" value="Add Item" style="width: 200px; background-color: #708951;"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login" style="background-image:url(https://cdn.visiteliti.com/article/2021-06/24/hihzEc6OEhQhDbao9DHi_1624529212.jpg); background-size: cover; background-position: center; background-repeat: no-repeat; background-size: cover;">
    <section class="vh-100" style="backdrop-filter: blur(20px);">
        <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5" >
            <div class="card shadow-2-strong" style="border-radius: 1rem; background-color: whitesmoke;">
                <div class="card-body p-5 text-center">
                    <form method="POST" action="">
                        <h1 class="mb-5" style="font-weight: bold; padding: 0px">Lontongistic</h1>
                        <h1 class="mb-5" style="font-weight: lighter; padding: 0px; font-size: 20px;">"Your digital inventory maestro"</h1>
                        {% csrf_token %}
                        <h3 class="mb-5" style="text-align: left;">Login</h3>
                        <div class="form-outline mb-4">
                            <input type="text" name="username" placeholder="Username" class="form-control">
                        </div>
            
                        <div class="form-outline mb-4">
                            <input type="password" name="password" placeholder="Password" class="form-control">
                        </div>
                        <div class="mb-4" style="padding-bottom:20px;">
                            Don't have an account yet? <a href="{% url 'main:register' %}" style="padding-left: 5px;"> Register Now </a>
                        </div>
                        {% if messages %}
                        <ul>
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}   
                        <input class="btn btn-primary btn-lg btn-block" type="submit" value="Login" style="width: 200px; background-color: #708951;">
                    </form>
                </div>
            </div>
            </div>
        </div>
        </div>
    </section>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .content{
            width: 100vw;
            height: 100vh;
            margin: 0;
            padding: 0; 
            background-image:url(https://cdn.visiteliti.com/article/2021-06/24/hihzEc6OEhQhDbao9DHi_1624529212.jpg); 
            background-size: cover; 
            background-position: center; 
            background-repeat: no-repeat; 
            background-size:cover;
            
        }

        .body{
            width: 100vw;
            height: 100vh;
            margin: 0; 
            padding: 0;
        }

        tr{
            border: 1px solid black;
            padding-right: 20px;
            padding-left: 20px;
            padding-top: 10px;
            padding-bottom: 10px;
            align-self: center;
            margin-left: auto;
            margin-right: auto;
            background-color: whitesmoke;
        }

        tr:last-child{
            background-color: #a6b993;
        }

        table, th, td{
            border: 1px solid black;
            padding-right: 20px;
            padding-left: 20px;
            padding-top: 10px;
            padding-bottom: 10px;
            align-self: center;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }
        th{
            background-color: #708951;
            color: white;
        }

        .card-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        .card {
            margin: 50px;
            border-radius: 10px;
            background-color: whitesmoke;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            width: 400px;
            height: 300px;
        }

        .card-header {
            background-color: #708951;
            text-align: center;
            padding: 10px;
        }

        .card-body {
            padding: 10px;
        }
        
        .card-footer{
            display: flex;
            justify-content: space-between;
            padding: 10px;
        }
        
        .card:last-child{
            background-color: #a6b993;
        }
    </style>
    <div class = "content">
        <nav class="navbar navbar-expand-lg" style="background-color: #708951; border-radius: 10px;">
            <div class="container-fluid">
            <a class="navbar-brand" href="#" style="font-size: 40px; font-weight: bold; padding: 10px; vertical-align: auto; color: whitesmoke;">Lontongistic</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="padding: 20px;">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="#" style="font-size: 25px; padding-left: 25px; padding-right: 25x; color: whitesmoke;">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:create_product' %}" style="font-size: 25px; padding-left: 25px; padding-right: 25px; color: whitesmoke;">Add Item</a>
                </li>
                <li class="nav-item">
                    <button class="nav-link" data-bs-toggle="modal" data-bs-target="#exampleModal" style="font-size: 25px; padding-left: 25px; padding-right: 25px; color: whitesmoke;">Add Item by AJAX</button>
                </li>
                </ul>
                <span class="navbar-text">
                    <a class="nav-link" href="{% url 'main:logout' %}" style="font-size: 25px; font-weight: bold; padding-left: 20px; padding-right: 20px; color: whitesmoke;">
                        Logout
                    </a>
                </span>
            </div>
            </div>
        </nav>
        <div class="body" style="backdrop-filter: blur(40px);">
            <div class="sub-body">
                <h5 style="padding: 20px; text-align: right; color: white;">Last Login : {{last_login}}</h5>
                <h2 style="padding: 20px; text-align: center; color: white;">Welcome to your digital inventory, {{name}} from {{class}}</h2>
            </div>
            <div class="card-container" id="card-product"> </div>
            <h5 id="item-amount" style="padding: 20px; text-align: center; color: white;"></h5>
            <br/>
        </div>
    </div>
    
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class= "form-control" id="amount" name="amount" min="1"></input>
                        </div>
                        <div class="mb-3">
                            <label for="category" class="col-form-label">Category:</label>
                            <textarea class="form-control" id="category" name="category"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
                </div>
            </div>
        </div>
    </div>
    

    <script>
        async function getProducts() {
            return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
        }

        async function refreshProducts() {
            const products = await getProducts()
            document.getElementById("card-product").innerHTML = ""
            let htmlStringCards = ``
            let totalItem = 0
            products.forEach((item) => {
                htmlStringCards += `
                <div class="card">
                    <div class="card-header" style="font-weight: bold; background-color: #708951; color: white;">${item.fields.name}</div>
                    <div class="card-body">
                        <p>Amount: ${item.fields.amount}</p>
                        <p>Description: ${item.fields.description}</p>
                        <p>Category: ${item.fields.category}</p>
                        <p>Date Added: ${item.fields.date_added}</p>
                    </div>
                    <div class="card-footer">
                        <a href='increase_item_amount/${item.pk}'>
                            <button type="submit" class="btn btn-primary" style="background-color:  #708951; color: white;">Increase</button>
                        </a>
                        <a href='decrease_item_amount/${item.pk}'>
                            <button type="submit" class="btn btn-danger" style="background-color:  #708951; color: white;">Decrease</button>
                        </a>
                        <a href='remove_item/${item.pk}'>
                            <button type="submit" class="btn btn-warning" style="background-color:  #708951; color: white;">Delete</button>
                        </a>
                        <button class="btn btn-warning" style="background-color:  #708951; color: white;" onclick="deleteItem(${item.pk})">Delete by AJAX</button>
                    </div>
                </div>
                `
                totalItem++
            })
            document.getElementById("card-product").innerHTML = htmlStringCards
            document.getElementById("item-amount").innerHTML = `There are ${totalItem} unique items in your inventory`
        }

        function addItem() {
            fetch("{% url 'main:add_item_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }

        function deleteItem(id) {
            fetch("/delete-item-ajax/" + id + "/", {
                method: "POST"
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }

        refreshProducts()
        document.getElementById("button_add").onclick = addItem
    </script>
        
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
<div class="register" style="background-image:url(https://cdn.visiteliti.com/article/2021-06/24/hihzEc6OEhQhDbao9DHi_1624529212.jpg); background-size: cover; background-position: center; background-repeat: no-repeat; background-size: cover;">
    <section class="vh-100" style="backdrop-filter: blur(20px);">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card shadow-2-strong" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">
                            <form method="POST">
                                {% csrf_token %} 
                                <h1 class="mb-5" style="font-weight: bold;">Register</h1>
                                <div class="form-outline mb-4">
                                    <input type="text"  name={{form.username.name}} placeholder="Username" class="form-control form-control-lg"/>
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="password" name={{form.password1.name}} placeholder="Password" class="form-control form-control-lg"/>
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="password" name={{form.password2.name}} placeholder="Confirm Password" class="form-control form-control-lg"/>
                                </div>
                                <input class="btn btn-primary btn-lg btn-block" type="submit" name="submit" value="Daftar" style="width: 200px; background-color: #708951;"/>
                            </form>
                            {% if messages %}  
                                <ul>   
                                    {% for message in messages %}  
                                        <li>{{ message }}</li>  
                                        {% endfor %}  
                                </ul>   
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock content %}